// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNETCoreAPI.Contexts;

namespace MyNETCoreAPI.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20210703201619_SampleData")]
    partial class SampleData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyNETCoreAPI.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new { Id = 1, Description = "Southwest desert city", Name = "El Paso" },
                        new { Id = 2, Description = "Heroic city in mexico", Name = "Juarez" },
                        new { Id = 3, Description = "City of futures market", Name = "Chicago" },
                        new { Id = 4, Description = "Home of Wallstreet", Name = "New York" }
                    );
                });

            modelBuilder.Entity("MyNETCoreAPI.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new { Id = 1, CityId = 1, Description = "Descrip of transmountain", Name = "Transmountain scenic park" },
                        new { Id = 2, CityId = 2, Description = "Descrip of point of int Juarez", Name = "Bars and Restaurants" },
                        new { Id = 3, CityId = 3, Description = "Descrip of point of int Chicago", Name = "The futures market building" },
                        new { Id = 4, CityId = 4, Description = "Wallstreet building", Name = "NYSE building" },
                        new { Id = 5, CityId = 4, Description = "City of Manhatan", Name = "Manhatan" }
                    );
                });

            modelBuilder.Entity("MyNETCoreAPI.Entities.PointOfInterest", b =>
                {
                    b.HasOne("MyNETCoreAPI.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
